name: splash_animation
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/ic_basket.svg
    - assets/images/ic_menu.svg
    - assets/images/ic_search.svg
    - assets/images/
    - assets/fonts/
    - assets/fonts/avenir/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir/AvenirLTStd-Black.otf
        - asset: assets/fonts/avenir/AvenirLTStd-Book.otf
        - asset: assets/fonts/avenir/AvenirLTStd-Roman.otf
