/// Generated by AssetsRefGenerator on 2022/05/19
class Res {
  static const String ic_basket = "assets/images/ic_basket.svg";
  static const String ic_menu = "assets/images/ic_menu.svg";
  static const String ic_search = "assets/images/ic_search.svg";
}
